---
- hosts: new
  become: yes
  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum: name=nginx state=present
  - name: Creates directory
    file:
      path: /etc/nginx/certs
      state: directory
      owner: nginx
      group: nginx
      mode: 0775

  - name: Add conf file
    copy:
      src: test.txt
      dest:  /usr/share/nginx/html/test.txt
  - name: Add conf file
    copy:
      src: static.conf
      dest: /etc/nginx/conf.d/static.conf
  - name: Add conf file
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
  - name: Add conf file
    copy:
      src: ssl.conf
      dest: /etc/nginx/conf.d/ssl.conf


  - name: Reload NGINX
    service:
      name: nginx
      state: reloaded 